name: Release with Changesets

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      version: ${{ steps.version.outputs.version }}
      tag_created: ${{ steps.tag.outputs.tag_created }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js (for changesets only)
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install changesets
        run: npm install -g @changesets/cli

      - name: Check for changesets
        id: changesets
        run: |
          if [ ! -d ".changeset" ] || [ -z "$(ls -A .changeset/*.md 2>/dev/null | grep -v README)" ]; then
            echo "has_changesets=false" >> $GITHUB_OUTPUT
            echo "No changesets found"
          else
            echo "has_changesets=true" >> $GITHUB_OUTPUT
            echo "Changesets found"
          fi

      - name: Generate version and changelog
        id: version
        if: steps.changesets.outputs.has_changesets == 'true'
        run: |
          # Generate changelog and consume changesets
          changeset version

          # Extract new version from changelog
          VERSION=$(grep "^## " CHANGELOG.md | head -1 | sed 's/## //')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          # Update Swift CLI version
          sed -i '' "s/version: \"[^\"]*\"/version: \"$VERSION\"/" Sources/CalvergeCLI.swift

      - name: Create Release PR or Release
        id: tag
        if: steps.changesets.outputs.has_changesets == 'true'
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Check if there are changes to commit
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit"
            echo "tag_created=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Commit changes
          git add -A
          git commit -m "chore: release v${VERSION}" || echo "Nothing to commit"

          # Create tag and push
          git tag "v${VERSION}"
          git push origin main
          git push origin "v${VERSION}"
          echo "tag_created=true" >> $GITHUB_OUTPUT

  build-release:
    runs-on: macos-latest
    needs: [release]
    if: |
      always() && 
      (startsWith(github.ref, 'refs/tags/v') || 
       (needs.release.result == 'success' && needs.release.outputs.tag_created == 'true'))
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
      checksum: ${{ steps.checksum.outputs.CHECKSUM }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ startsWith(github.ref, 'refs/tags/v') && github.ref || format('refs/tags/v{0}', needs.release.outputs.version) }}

      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9"

      - name: Get version
        id: version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            # Triggered by tag push
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            # Triggered after release job
            echo "VERSION=${{ needs.release.outputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and sign executable
        run: |
          # Build release binary
          swift build -c release

          # Sign the executable (ad-hoc signing)
          codesign --force --sign - --entitlements calverge.entitlements .build/release/calverge

      - name: Create archive
        run: |
          mkdir -p release
          cp .build/release/calverge release/
          tar -czf calverge-${{ steps.version.outputs.VERSION }}-macos.tar.gz -C release .

      - name: Calculate checksum
        id: checksum
        run: |
          CHECKSUM=$(shasum -a 256 calverge-${{ steps.version.outputs.VERSION }}-macos.tar.gz | cut -d ' ' -f 1)
          echo "CHECKSUM=$CHECKSUM" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            calverge-${{ steps.version.outputs.VERSION }}-macos.tar.gz
          body: |
            ## Changes

            See the [changelog](CHANGELOG.md) for details.

            ## Installation

            ### Homebrew (Recommended)
            ```bash
            brew install lgastler/tap/calverge
            ```

            ### Manual Installation
            ```bash
            curl -L https://github.com/${{ github.repository }}/releases/download/v${{ steps.version.outputs.VERSION }}/calverge-${{ steps.version.outputs.VERSION }}-macos.tar.gz | tar xz
            sudo mv calverge /usr/local/bin/
            ```

            **SHA256 Checksum:** `${{ steps.checksum.outputs.CHECKSUM }}`
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-homebrew:
    runs-on: ubuntu-latest
    needs: [build-release]
    if: success() && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Update Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: calverge
          formula-path: Formula/calverge.rb
          homebrew-tap: lgastler/homebrew-tap
          download-url: https://github.com/${{ github.repository }}/releases/download/v${{ needs.build-release.outputs.version }}/calverge-${{ needs.build-release.outputs.version }}-macos.tar.gz
          commit-message: |
            {{formulaName}} {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
