name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9"
      - name: Build
        run: swift build

  release:
    runs-on: macos-latest
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/v')
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
      checksum: ${{ steps.checksum.outputs.CHECKSUM }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9"

      - name: Get version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update Swift version
        run: |
          cat > update-swift-version.js << 'EOF'
          const fs = require('fs');
          const version = process.argv[2];
          const swiftFile = 'Sources/CalvergeCLI.swift';

          let content = fs.readFileSync(swiftFile, 'utf8');
          content = content.replace(/version: "[^"]*"/, `version: "${version}"`);
          fs.writeFileSync(swiftFile, content);
          console.log(`Updated Swift version to ${version}`);
          EOF

          node update-swift-version.js "${{ steps.version.outputs.VERSION }}"

      - name: Build and sign executable
        run: |
          swift build -c release
          codesign --force --sign - --entitlements calverge.entitlements .build/release/calverge

      - name: Create archive
        run: |
          mkdir -p release
          cp .build/release/calverge release/
          tar -czf calverge-${{ steps.version.outputs.VERSION }}-macos.tar.gz -C release .

      - name: Calculate checksum
        id: checksum
        run: |
          CHECKSUM=$(shasum -a 256 calverge-${{ steps.version.outputs.VERSION }}-macos.tar.gz | cut -d ' ' -f 1)
          echo "CHECKSUM=$CHECKSUM" >> $GITHUB_OUTPUT

      - name: Get Changelog for Release
        id: changelog
        run: |
          # Extract content for the current version from CHANGELOG.md
          # Assumes CHANGELOG.md has headings like "## [X.Y.Z] - YYYY-MM-DD"
          # and extracts content until the next heading or end of file.
          VERSION_TAG="v${{ steps.version.outputs.VERSION }}"
          CHANGELOG_CONTENT=$(awk -v RS="## " -v VERSION="${{ steps.version.outputs.VERSION }}" '/^\[VERSION\]/{print "## "$0; exit}' CHANGELOG.md)
          # Remove the version heading itself from the content
          CHANGELOG_CONTENT=$(echo "$CHANGELOG_CONTENT" | sed -n "/^\[${{ steps.version.outputs.VERSION }}\]/!p")
          # Trim leading/trailing whitespace
          CHANGELOG_CONTENT=$(echo "$CHANGELOG_CONTENT" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
          
          # Escape newlines for multiline output
          ESCAPED_CHANGELOG_CONTENT="$(echo "$CHANGELOG_CONTENT" | sed -z 's/\n/%0A/g')"
          echo "CHANGELOG_BODY=$ESCAPED_CHANGELOG_CONTENT" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          files: |
            calverge-${{ steps.version.outputs.VERSION }}-macos.tar.gz
          body: ${{ steps.changelog.outputs.CHANGELOG_BODY }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-homebrew:
    runs-on: ubuntu-latest
    needs: [release]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Update Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: calverge
          formula-path: Formula/calverge.rb
          homebrew-tap: lgastler/homebrew-tap
          download-url: https://github.com/${{ github.repository }}/releases/download/v${{ needs.release.outputs.version }}/calverge-${{ needs.release.outputs.version }}-macos.tar.gz
          commit-message: |
            {{formulaName}} {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}